version: '3.8'

services:
  preamly:
    image: preamly-api
    container_name: preamly-api
    build:
      dockerfile: api.Dockerfile
      args:
        MONGO_API_CONN_STR: ${MONGO_API_CONN_STR}
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3001 || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: preamly-db
    container_name: preamly-db
    build:
      dockerfile: db.Dockerfile
      args:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_PORT:          ${MONGO_INITDB_PORT}
        MONGO_API_DB:               ${MONGO_API_DB}
        MONGO_API_USER:             ${MONGO_API_USER}
        MONGO_API_PASS:             ${MONGO_API_PASS}
    volumes:
      - preamlydb:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 20s
      timeout: 10s
      retries: 5

volumes:
  preamlydb:
    driver: local