services:
  preamly:
    image: preamly
    restart: always
    ports:
      - 3000:3000
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: preamly
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_PORT: 27017
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: preamly
      MONGO_INITDB_HOST: mongo
      MONGO_INITDB_PORT: 27017
    ports:
      - 27017:27017
    healthcheck:
      test: mongo --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
